global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval:1h
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'email@example.com'
        from: 'alertamanager@example.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'your_mail@example.com'
        auth_password: '${auth_passwrd}'
